### ISSUE TITLE
Fatal: Concurrent Map Writes

### ISSUE THREAD

**Issue by eliquious** [rs/xlog#12]
I'm experiencing fatal errors at 60k+ requests per second. It seems like the issue is in `SetField` since there's not a lock around it. The issue arrises when using the `xlog.URLHandler("path")` and `xlog.MethodHandler("method")` middleware.

Any thoughts on the simplest fix?

**Comment by rs** [comment]
I don't really understand how those handlers could concurrently access the map. Each context get a separate copy of the xlogger, and a given http request doesn't run its handlers concurrently.

Could you give me some more info on the way you use xlog?

**Comment by eliquious** [comment]
I _just_ saw your comment from last week. :/ But I think you just helped me figure out the issue. I'm _not_ using `xlog.FromContext` for each request. I'm using a reference to a logger created previously. Like so:

```go
type Handler {
    logger xlog.Logger
}

func (h *Handler) Get(ctx context.Context, w http.ResponseWriter, r *http.Request) {
    h.logger.Info("Inside GET")
}
```

Which based on your comments, is likely wrong... Is the following usage correct?

```go
type Handler {
}

func (h *Handler) Get(ctx context.Context, w http.ResponseWriter, r *http.Request) {
    logger := xlog.FromContext(ctx)
    logger.Info("Inside GET")
}
```

**Comment by rs** [comment]
Yes, that’s the way to go if you installed xlog handler. You can also use Copy() to get a copy of your global logger.
