### ISSUE TITLE
Simple code does not output anything

### ISSUE THREAD

**Issue by trong** [rs/xlog#4]
The code below does not output anything
```go
package main 

import (
	"github.com/rs/xlog"
)

func main() {
	l := xlog.New(xlog.Config{})
	l.Infof("%s", "INFO")
}
```
Could you say - whats is wrong?

**Comment by rs** [comment]
By default the output is wrapped into a OutputChannel so there is a buffered channel between the logger and the output. It’s well suited for http handler so logging output I/O can never block your handlers.

When used like that, your program will exit before the buffered channel is actually flushed and delivered to the output.

**Comment by trong** [comment]
Ok, thanks!
